Repository unan25/TodayTrend, pull requests merged in 2023-12, with the labels that each got.

#63 feat: Gateway 인증/인가 필터 구현
  apigateway-server/build.gradle
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/filter/AuthFilter.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/filter/LogFilter.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/filter/exceptionpath/ExceptionPathManager.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/jwt/JwtProperties.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/jwt/TokenProvider.java
  apigateway-server/src/main/resources/application-jwt.yml
  apigateway-server/src/main/resources/application.yml
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  auth-service/src/main/java/com/todaytrend/authservice/controller/AuthController.java
  auth-service/src/main/java/com/todaytrend/authservice/domain/SocialUser.java
  auth-service/src/main/java/com/todaytrend/authservice/domain/enum_/Role.java
  auth-service/src/main/java/com/todaytrend/authservice/dto/CreateSocialUserDto.java
  auth-service/src/main/java/com/todaytrend/authservice/service/SocialUserService.java
  auth-service/src/main/java/com/todaytrend/authservice/service/UserService.java
  front-end/src/interface/UserInterface.ts
  front-end/src/redux/_actions/user_action.ts
  front-end/src/views/components/NavBar/NabBar.tsx
  front-end/src/views/page/SignInPage/SignInPage.tsx
  front-end/src/views/page/SignUpPage/SignUpPage.tsx
  image-service/build.gradle
  image-service/src/main/resources/application.yml
  post-service/build.gradle
  post-service/src/main/java/com/todaytrend/postservice/PostServiceApplication.java
  post-service/src/main/resources/application.yml
  user-service/src/main/java/com/todaytrend/userservice/controller/UserController.java
  user-service/src/main/java/com/todaytrend/userservice/repository/UserRepository.java
  user-service/src/main/java/com/todaytrend/userservice/service/UserService.java
Labels: 윤환

#66 feat: 해시태그 구분 로직 추가, 이미지 크롭 초기 구현
  front-end/global.css
  front-end/src/App.tsx
  front-end/src/views/components/CateogoryBox/CategoryBox.module.css
  front-end/src/views/components/CateogoryBox/CategoryBox.tsx
  front-end/src/views/components/CateogoryBox/CategoryModal/CategoryModal.module.css
  front-end/src/views/components/CateogoryBox/CategoryModal/CategoryModal.tsx
  front-end/src/views/components/DropZone/PostDropZone/ImageCropModal.tsx
  front-end/src/views/components/DropZone/PostDropZone/PostDropZone.module.css
  front-end/src/views/components/DropZone/PostDropZone/PostDropZone.tsx
  front-end/src/views/components/TextWithHashtag/TextWithHashtag.tsx
  front-end/src/views/components/common/AlertBox/AlertBox.module.css
  front-end/src/views/components/common/AlertBox/AlertBox.tsx
  front-end/src/views/components/common/NavBar/NabBar.module.css
  front-end/src/views/components/common/NavBar/NabBar.tsx
  front-end/src/views/components/common/OnChangeInput/OnChangeInput.modules.css
  front-end/src/views/components/common/OnChangeInput/OnChangeInput.tsx
  front-end/src/views/components/common/SelectBox/SelectBox.module.css
  front-end/src/views/components/common/SelectBox/SelectBox.tsx
  front-end/src/views/components/common/Sidebar/SideBar.module.css
  front-end/src/views/components/common/Sidebar/SideBar.tsx
  front-end/src/views/components/dropzone/PostDropZone/ImageCropModal/ImageCropModal.module.css
  front-end/src/views/components/dropzone/PostDropZone/ImageCropModal/ImageCropModal.tsx
  front-end/src/views/components/user/AccountForm/AccountForm.module.css
  front-end/src/views/components/user/AccountForm/AccountForm.tsx
  front-end/src/views/components/user/SocialLoginButton/Google/GoogleLogin.module.css
  front-end/src/views/components/user/SocialLoginButton/Google/GoogleLogin.tsx
  front-end/src/views/components/user/SocialLoginButton/Google/GoogleLoginService.ts
  front-end/src/views/components/user/SocialLoginButton/Kakao/KakaoLogin.module.css
  front-end/src/views/components/user/SocialLoginButton/Kakao/KakaoLogin.tsx
  front-end/src/views/components/user/SocialLoginButton/Kakao/KakaoLoginService.ts
  front-end/src/views/components/user/UserInfoForm/UserInfoForm.module.css
  front-end/src/views/components/user/UserInfoForm/UserInfoForm.tsx
  front-end/src/views/page/LandingPage/LandingPage.tsx
  front-end/src/views/page/SignInPage/SignInPage.tsx
  front-end/src/views/page/SignUpPage/SignUpPage.tsx
  front-end/src/views/page/UploadPostPage/UploadPostPage.module.css
  front-end/src/views/page/UploadPostPage/UploadPostPage.tsx
Labels: 승혁

#68 feat: Auth PW찾기 구현(SMTP)
  .gitignore
  auth-service/.gitignore
  auth-service/.gradle/8.4/checksums/checksums.lock
  auth-service/.gradle/8.4/checksums/md5-checksums.bin
  auth-service/.gradle/8.4/checksums/sha1-checksums.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  auth-service/.idea/modules.xml
  auth-service/.idea/modules/auth-service.test.iml
  auth-service/build.gradle
  auth-service/src/main/java/com/todaytrend/authservice/controller/AuthController.java
  auth-service/src/main/java/com/todaytrend/authservice/domain/LocalUser.java
  auth-service/src/main/java/com/todaytrend/authservice/dto/MailDto.java
  auth-service/src/main/java/com/todaytrend/authservice/service/EmailService.java
  auth-service/src/main/java/com/todaytrend/authservice/service/UserEmailService.java
  auth-service/src/main/java/com/todaytrend/authservice/service/UserService.java
  auth-service/src/main/resources/application-smtp.yml
  auth-service/src/main/resources/application.yml
  user-service/src/main/java/com/todaytrend/userservice/controller/UserController.java
  user-service/src/main/java/com/todaytrend/userservice/domain/User.java
  user-service/src/main/java/com/todaytrend/userservice/dto/RequestCreateUserDto.java
  user-service/src/main/java/com/todaytrend/userservice/dto/ResponseImgAndNicknameDto.java
  user-service/src/main/java/com/todaytrend/userservice/repository/UserRepository.java
  user-service/src/main/java/com/todaytrend/userservice/service/UserService.java
  user-service/src/test/java/com/todaytrend/userservice/ServerServiceTest.java
Labels: 윤환

#70 feat: 포스트 업로드 비동기 요청
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  front-end/src/redux/store.ts
  front-end/src/views/components/CateogoryBox/CategoryBox.module.css
  front-end/src/views/components/CateogoryBox/CategoryBox.tsx
  front-end/src/views/components/CateogoryBox/CategoryModal/CategoryModal.module.css
  front-end/src/views/components/CateogoryBox/CategoryModal/CategoryModal.tsx
  front-end/src/views/components/TextWithHashtag/TextWithHashtag.tsx
  front-end/src/views/components/user/UserInfoForm/UserInfoForm.tsx
  front-end/src/views/page/UploadPostPage/UploadPostPage.tsx
  post-service/build.gradle
  post-service/src/main/java/com/todaytrend/postservice/PostServiceApplication.java
  post-service/src/main/java/com/todaytrend/postservice/post/Excepion/ExceptionController.java
  post-service/src/main/java/com/todaytrend/postservice/post/controller/PostController.java
  post-service/src/main/java/com/todaytrend/postservice/post/dto/CRUD/responseMakePostDto.java
  post-service/src/main/java/com/todaytrend/postservice/post/service/PostServiceImpl.java
  post-service/src/main/resources/application.yml
Labels: 승혁

#85 feat: Front - PW변경 페이지 구현
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/WebSecurityConfig.java
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  auth-service/src/main/java/com/todaytrend/authservice/controller/AuthController.java
  front-end/.vscode/settings.json
  front-end/src/App.tsx
  front-end/src/views/page/ChangePwPage/ChangePwPage.module.css
  front-end/src/views/page/ChangePwPage/ChangePwPage.tsx
  user-service/src/main/java/com/todaytrend/userservice/controller/UserController.java
  user-service/src/main/java/com/todaytrend/userservice/service/UserService.java
Labels: 윤환

#93 feature: 게시물 상세 페이지 비동기 요청, 프론트 likes 구현
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  front-end/src/App.tsx
  front-end/src/views/components/CateogoryBox/CategoryModal/CategoryModal.tsx
  front-end/src/views/components/common/NavBar/NabBar.module.css
  front-end/src/views/components/common/NavBar/NabBar.tsx
  front-end/src/views/components/post/PostLikesButton/PostLikesButton.module.css
  front-end/src/views/components/post/PostLikesButton/PostLikesButton.tsx
  front-end/src/views/components/post/PostList/PostList.tsx
  front-end/src/views/components/user/FollowListModal/FollowListModal.tsx
  front-end/src/views/page/PostDetailPage/PostDetailPage.module.css
  front-end/src/views/page/PostDetailPage/PostDetailPage.tsx
  front-end/src/views/page/ProfilePage/ProfilePage.tsx
  front-end/src/views/page/UploadPostPage/UploadPostPage.tsx
  post-service/src/main/java/com/todaytrend/postservice/post/feign/user/UserFeignClient.java
  user-service/src/main/java/com/todaytrend/userservice/controller/UserController.java
  user-service/src/main/java/com/todaytrend/userservice/service/FollowService.java
Labels: 승혁

#95 refactor: 게이트웨이 시큐리티 수정
  apigateway-server/build.gradle
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/CookieServerAuthenticationConverter.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/WebSecurityConfig.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/exceptionpath/ExceptionPathManager.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/jwt/TokenProvider.java
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  auth-service/src/main/java/com/todaytrend/authservice/util/CookieUtils.java
  user-service/src/main/java/com/todaytrend/userservice/controller/ServerController.java
Labels: 윤환

#102 feat : front - 최근 검색목록 및 해시태그 검색페이지 추가
  front-end/src/App.tsx
  front-end/src/views/components/post/PostImage/PostImage.module.css
  front-end/src/views/components/post/PostList/PostList.module.css
  front-end/src/views/page/LandingPage/LandingPage.module.css
  front-end/src/views/page/LandingPage/LandingPage.tsx
  front-end/src/views/page/SearchHashTagPage/SearchHashTagPage.module.css
  front-end/src/views/page/SearchHashTagPage/SearchHashTagPage.tsx
  front-end/src/views/page/SearchPage/SearchPage.module.css
  front-end/src/views/page/SearchPage/SearchPage.tsx
  post-service/src/main/java/com/todaytrend/postservice/post/controller/PostController.java
Labels: 성민

#105 feat: 토큰 재발급 구현
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/CookieServerAuthenticationConverter.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/CustomReactiveAuthenticationManager.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/WebSecurityConfig.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/exceptionpath/ExceptionPathManager.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/jwt/JwtAuthenticationToken.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/jwt/TokenProvider.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/security/UserDetailsImpl.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/filter/LogFilter.java
  apigateway-server/src/main/resources/application.yml
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  auth-service/src/main/java/com/todaytrend/authservice/config/jwt/TokenProvider.java
  auth-service/src/main/java/com/todaytrend/authservice/controller/AuthController.java
  auth-service/src/main/java/com/todaytrend/authservice/service/TokenService.java
  auth-service/src/main/java/com/todaytrend/authservice/util/CookieUtils.java
  auth-service/src/main/resources/application.yml
  front-end/src/api.ts
  front-end/src/views/page/ProfilePage/ProfilePage.tsx
  image-service/src/main/resources/application.yml
  post-service/src/main/resources/application.yml
  user-service/src/main/resources/application.yml
Labels: 윤환

#114 build: build 파일 및 Dockerfile 생성
  apigateway-server/Dockerfile
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/WebSecurityConfig.java
  apigateway-server/src/main/java/com/todaytrend/apigatewayserver/config/exceptionpath/ExceptionPathManager.java
  apigateway-server/src/main/resources/application.yml
  auth-service/.gradle/8.4/executionHistory/executionHistory.bin
  auth-service/.gradle/8.4/executionHistory/executionHistory.lock
  auth-service/.gradle/8.4/fileHashes/fileHashes.bin
  auth-service/.gradle/8.4/fileHashes/fileHashes.lock
  auth-service/.gradle/8.4/fileHashes/resourceHashesCache.bin
  auth-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  auth-service/.gradle/file-system.probe
  auth-service/Dockerfile
  auth-service/src/main/resources/application-db.yml
  auth-service/src/main/resources/application.yml
  auth-service/src/test/java/com/todaytrend/authservice/config/jwt/JwtFactory.java
  auth-service/src/test/java/com/todaytrend/authservice/config/jwt/TokenProviderTest.java
  auth-service/src/test/java/com/todaytrend/authservice/controller/TokenApiController.java
  eureka-server/Dockerfile
  front-end/Dockerfile
  image-service/Dockerfile
  image-service/src/main/resources/application.yml
  post-service/Dockerfile
  post-service/src/main/resources/application.yml
  user-service/Dockerfile
  user-service/src/main/resources/application.yml
Labels: 윤환
